### ISSUE TITLE
 Invalid signature file digest for Manifest

### ISSUE THREAD

**Issue by bmweller** [ShorTie8/Arduino_IDE#1]
I have succesfully built and installed the debianized version for the PI using this source package however when I lauch I'm getting this error, has this been seen before?

java.lang.SecurityException: Invalid signature file digest for Manifest main attributes

arduino
Picked up JAVA_TOOL_OPTIONS: 
Error parsing gtk-icon-sizes string: ''
java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
    at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:238)
    at sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:192)
    at java.util.jar.JarVerifier.processEntry(JarVerifier.java:316)
    at java.util.jar.JarVerifier.update(JarVerifier.java:228)
    at java.util.jar.JarFile.initializeVerifier(JarFile.java:383)
    at java.util.jar.JarFile.getInputStream(JarFile.java:450)
    at sun.misc.URLClassPath$JarLoader$2.getInputStream(URLClassPath.java:776)
    at sun.misc.Resource.cachedInputStream(Resource.java:77)
    at sun.misc.Resource.getByteBuffer(Resource.java:160)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at cc.arduino.contributions.packages.ContributionsIndexer.isSigned(ContributionsIndexer.java:169)
    at cc.arduino.contributions.packages.ContributionsIndexer.parseIndex(ContributionsIndexer.java:82)
    at processing.app.BaseNoGui.initPackages(BaseNoGui.java:628)
    at processing.app.Base.<init>(Base.java:299)
    at processing.app.Base.guardedMain(Base.java:226)
    at processing.app.Base.main(Base.java:137)
cc.arduino.contributions.SignatureVerificationFailedException: package_index.json file signature verification failed
    at cc.arduino.contributions.packages.ContributionsIndexer.parseIndex(ContributionsIndexer.java:83)
    at processing.app.BaseNoGui.initPackages(BaseNoGui.java:628)
    at processing.app.Base.<init>(Base.java:299)
    at processing.app.Base.guardedMain(Base.java:226)
    at processing.app.Base.main(Base.java:137)

**Comment by ShorTie8** [comment]
L00ks like you used 1.6.6

**Comment by bmweller** [comment]
I downloaded release 1.6.5-r3

Is it just a case of recomputing the hashes?

**Comment by theGitHubguy15** [comment]
Try pasting this in your terminal:
(First remove your installation directory and make sure you have at leas 1GB of space for the temporay files.)
```
cd
sudo apt-get remove arduino
wget https://github.com/arduino/Arduino/archive/1.6.5.tar.gz
tar xf 1.6.5.tar.gz
cd Arduino-1.6.5
git clone https://github.com/ShorTie8/Arduino_IDE
ln -s Arduino_IDE/debian debian

# build dependencies for Arduino IDE
sudo apt-get install devscripts -y
mk-build-deps

# the next line will create dependency warnings which will be fixed afterwards
sudo dpkg -i arduino-build-deps_1.6.5_all.deb

# clean up dependencies
sudo apt-get -f install -y

# make some space
sudo apt-get autoremove -y
sudo apt-get autoclean
sudo apt-get clean

# build and install
dpkg-buildpackage -uc -b -tc
cd ..
sudo dpkg -i arduino-core_1.6.5_all.deb arduino_1.6.5_all.deb
```
